### ISSUE TITLE
preflight checklist

### ISSUE THREAD

**Issue by ParadauxIO** [Aberdeener/1620-assignment-1#54]
- [ ] EMERGENCY  EQUIPMENT -> Checked
- [ ] FIRE  PROTECTION -> Checked
- [ ] INTERRUPT  SWITCHES -> on
- [ ] PASSENGER  OXYGEN -> Normal
- [ ] STAB  TRIM  CUTOUT  SWITCHES -> AUTO
- [ ] NAV  EQUIPMENT -> CHECKED
- [ ] OXYGEN  AND  INTERPHONE -> CHECKED
- [ ] GEAR  PINS -> STOWED
- [ ] FLIGHTDECK  LIGHTS -> SET
- [ ] SERVICEABILITY -> CHECKED
- [ ] FMC -> SET/CHECKED
- [ ] CREW  BRIEFING -> COMPLETED
- [ ] EEC  PUSHBUTTONS -> NORMAL
- [ ] IRS -> NAV
- [ ] HYDRAULIC  SYSTEM -> SET
- [ ] EMERGENCY  LIGHTS -> ARMED
- [ ] AUDIO  SYSTEMS -> NORMAL
- [ ] INTERPHONE  SWITCHES -> OFF
- [ ] ANTI-ICE SYSTEMS -> OFF
- [ ] WINDOW  HEAT -> ON
- [ ] YAW  DAMPERS -> ON
- [ ] VOICE RECORDER ->ON
- [ ] PRESSURIZATION -> SET
- [ ] AIRCONDITIONING -> SET
- [ ] BLEED  PANEL -> SET
- [ ] EXTERIOR  LIGHTS  (WING/LOGO) -> SET
- [ ] EFIS  CONTROL  PANELS -> SET
- [ ] MODE CONTROL PANEL -> SET
- [ ] STANDBY  INSTRUMENTS -> SET
- [ ] SPEEDBRAKES -> RETRACTED
- [ ] THRUST LEVERS -> DOWN AND CLOSED
- [ ] PARKING  BRAKES -> SET
- [ ] FUEL CONTROL SWITCHES -> CUTOFF
- [ ] COMMUNICATIONS -> SET
- [ ] RADAR -> SET
- [ ] NO  SMOKING  SIGN -> ON
- [ ] EVAC  SIGNAL -> ARM
